language: ruby
gemfile:
  - gemfiles/activesupport23.gemfile
  - gemfiles/activesupport30.gemfile
  - gemfiles/activesupport31.gemfile
  - gemfiles/activesupport32.gemfile
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/activesupport23.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/activesupport23.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/activesupport23.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/activesupport23.gemfile
    - rvm: rbx-19mode
      gemfile: gemfiles/activesupport23.gemfile
